from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class GraphBuildStageDescriptor:
    name: str
    owner: str
    function: str
    responsibility: str
    worst_case_complexity: str
    complexity_reason: str


def build_graph_stage_catalog() -> list[GraphBuildStageDescriptor]:
    return [
        GraphBuildStageDescriptor(
            name="document_graph_builder.initialize_document",
            owner="DocumentGraphBuilder",
            function="build",
            responsibility="Create the document aggregate and builder factories.",
            worst_case_complexity="O(1)",
            complexity_reason="Constant-size object creation.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.sort_elements",
            owner="SectionBuilder",
            function="build",
            responsibility="Sort canonical elements by reading order.",
            worst_case_complexity="O(n log n)",
            complexity_reason="Single sort across all canonical elements.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.collect_headers",
            owner="SectionBuilder",
            function="build",
            responsibility="Filter section headers and sort them.",
            worst_case_complexity="O(n + h log h)",
            complexity_reason="Single scan for headers plus header-only sort.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.resolve_hierarchy",
            owner="SectionHierarchyResolver",
            function="resolve",
            responsibility="Infer heading levels and explicit parent relationships.",
            worst_case_complexity="O(h^2 + n)",
            complexity_reason="Header-pair heuristics with one full element pass.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.build_section_stack",
            owner="SectionStackBuilder",
            function="build",
            responsibility="Convert heading levels into section entities.",
            worst_case_complexity="O(h)",
            complexity_reason="Single pass over filtered headers.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.build_leading_root_section",
            owner="SectionBuilder",
            function="_build_leading_root_section",
            responsibility="Create an initial root section when content precedes the first heading.",
            worst_case_complexity="O(n)",
            complexity_reason="Single pass until the first header boundary.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.relink_section_paths",
            owner="SectionPathRelinker",
            function="relink",
            responsibility="Rebuild full section paths from parent relationships.",
            worst_case_complexity="O(s * d)",
            complexity_reason="Each section rebuilds a path across its ancestor depth.",
        ),
        GraphBuildStageDescriptor(
            name="section_builder.assign_elements_to_sections",
            owner="SectionBuilder",
            function="build",
            responsibility="Assign each canonical element to the current active section.",
            worst_case_complexity="O(n)",
            complexity_reason="Single ordered pass over canonical elements.",
        ),
        GraphBuildStageDescriptor(
            name="document_graph_builder.add_sections",
            owner="DocumentGraphBuilder",
            function="build",
            responsibility="Insert built sections into the graph aggregate.",
            worst_case_complexity="O(s)",
            complexity_reason="Single pass over section entities.",
        ),
        GraphBuildStageDescriptor(
            name="document_graph_builder.materialize_elements_assets",
            owner="DocumentGraphBuilder",
            function="build",
            responsibility="Create domain elements and associated table/picture assets.",
            worst_case_complexity="O(n)",
            complexity_reason="Single ordered pass over canonical elements.",
        ),
        GraphBuildStageDescriptor(
            name="document_graph_builder.asset_nearby_text_enrichment",
            owner="AssetNearbyTextEnricher",
            function="enrich",
            responsibility="Attach nearby textual context to table and picture assets.",
            worst_case_complexity="O(a * w)",
            complexity_reason="Each asset inspects a bounded section-local window.",
        ),
        GraphBuildStageDescriptor(
            name="graph_chunk_builder.order_sections",
            owner="GraphChunkBuilder",
            function="build_chunks",
            responsibility="Sort sections for chunk generation.",
            worst_case_complexity="O(s log s)",
            complexity_reason="Single sort across sections.",
        ),
        GraphBuildStageDescriptor(
            name="graph_chunk_builder.index_section_elements",
            owner="GraphChunkBuilder",
            function="build_chunks",
            responsibility="Resolve section-local element lists for chunking.",
            worst_case_complexity="O(n + s)",
            complexity_reason="Each section projects its assigned element ids once.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.create_runtime",
            owner="ChunkingRuntimeFactory",
            function="create",
            responsibility="Resolve chunking runtime strategy objects and policies.",
            worst_case_complexity="O(s)",
            complexity_reason="Runtime selection inspects document and section metadata.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.order_sections",
            owner="SectionChunkBuilder",
            function="build_document_chunk_payloads",
            responsibility="Sort sections before fragment generation.",
            worst_case_complexity="O(s log s)",
            complexity_reason="Single sort across sections.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.build_section_lookup",
            owner="SectionChunkBuilder",
            function="build_document_chunk_payloads",
            responsibility="Create section-path lookup structures for payload ownership.",
            worst_case_complexity="O(s)",
            complexity_reason="Single pass across ordered sections.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.combine_document_section_text",
            owner="SectionChunkBuilder",
            function="build_document_chunk_payloads",
            responsibility="Assemble document-wide section path text for structural heuristics.",
            worst_case_complexity="O(s * d)",
            complexity_reason="Joins each section path once.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.build_fragments",
            owner="ChunkFragmentBuilder",
            function="build_section_fragments",
            responsibility="Produce section fragments from section content and structured evidence.",
            worst_case_complexity="O(n + f)",
            complexity_reason="Linear scans over section elements plus structured fragment windows.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.build_base_payloads",
            owner="SectionChunkBuilder",
            function="_chunk_payloads_from_fragments",
            responsibility="Merge fragments into payload windows and resolve chunk types.",
            worst_case_complexity="O(f + p)",
            complexity_reason="Single fragment walk with bounded overlap handling and payload creation.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.build_overviews",
            owner="SectionOverviewChunkBuilder",
            function="build",
            responsibility="Generate overview chunks for section context.",
            worst_case_complexity="O(s + n)",
            complexity_reason="Walk sections and their assigned elements once.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.merge_overviews",
            owner="SectionChunkBuilder",
            function="_merge_overview_payloads",
            responsibility="Insert overview payloads ahead of matching base payload families.",
            worst_case_complexity="O(p * o)",
            complexity_reason="Each base payload checks candidate overview paths.",
        ),
        GraphBuildStageDescriptor(
            name="section_chunk_builder.deduplicate_payloads",
            owner="ChunkPayloadDeduplicator",
            function="deduplicate",
            responsibility="Collapse duplicate or companion payload families.",
            worst_case_complexity="O(p * b)",
            complexity_reason="Indexed candidate comparison across related payload buckets rather than all payload pairs.",
        ),
        GraphBuildStageDescriptor(
            name="graph_chunk_builder.materialize_chunks",
            owner="GraphChunkBuilder",
            function="build_chunks",
            responsibility="Create final DocumentChunk entities from payloads.",
            worst_case_complexity="O(p)",
            complexity_reason="Single pass over payloads.",
        ),
        GraphBuildStageDescriptor(
            name="document_graph_builder.aggregate_chunk_signals",
            owner="DocumentGraphBuilder",
            function="build",
            responsibility="Aggregate section-level chunk signals and chunk-type counts.",
            worst_case_complexity="O(c)",
            complexity_reason="Single pass over final chunks.",
        ),
        GraphBuildStageDescriptor(
            name="document_graph_builder.compute_statistics",
            owner="DocumentGraphBuilder",
            function="build",
            responsibility="Persist final document statistics on the aggregate.",
            worst_case_complexity="O(1)",
            complexity_reason="Constant-size statistics object creation.",
        ),
    ]
