from src.domain.common import ChunkType, SourceLocation
from src.domain.retrieval import RetrievalQuery, RetrievedChunk
from src.infrastructure.retrieval.rerankers import DeterministicHybridReranker


def make_chunk(
    *,
    chunk_id: str,
    content: str,
    chunk_type: ChunkType,
    score: float,
    section_path: list[str],
    metadata: dict[str, str] | None = None,
) -> RetrievedChunk:
    return RetrievedChunk(
        chunk_id=chunk_id,
        document_id="doc_001",
        content=content,
        score=score,
        retrieval_source="hybrid",
        chunk_type=chunk_type,
        section_id="sec_001",
        section_path=section_path,
        source=SourceLocation(page_start=1, page_end=1),
        metadata=metadata or {},
    )


def test_deterministic_hybrid_reranker_prefers_atomic_identifier_evidence() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_001",
        query_text="What does ordering code MK311007 mean?",
        detected_identifiers=["mk311007"],
    )
    overview_chunk = make_chunk(
        chunk_id="chunk_overview",
        content="Section overview: ordering code MK311007 appears in this table.",
        chunk_type=ChunkType.OVERVIEW,
        score=0.95,
        section_path=["Ordering example"],
        metadata={"sql_keyword_source_score": "4.0"},
    )
    atomic_chunk = make_chunk(
        chunk_id="chunk_atomic",
        content="MK311007 = 2-way Wafer-type Ball valve, stainless steel, handle, DN 50.",
        chunk_type=ChunkType.TECHNICAL_SPECIFICATION,
        score=0.72,
        section_path=["Ordering example"],
        metadata={
            "sql_keyword_source_score": "18.0",
            "sql_exact_identifier_matches": "1",
        },
    )

    reranked = reranker.rerank(query, [overview_chunk, atomic_chunk])

    assert reranked[0].chunk_id == "chunk_atomic"


def test_deterministic_hybrid_reranker_prefers_procedure_chunks_over_overviews() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_002",
        query_text="How do I start and run the macerator?",
    )
    overview_chunk = make_chunk(
        chunk_id="chunk_overview",
        content="Section overview: Manual Operation Page 6.1.4",
        chunk_type=ChunkType.OVERVIEW,
        score=0.98,
        section_path=["6 Operation & General Maintenance", "Manual Operation Page 6.1.4"],
        metadata={"sql_keyword_source_score": "3.0"},
    )
    procedure_chunk = make_chunk(
        chunk_id="chunk_procedure",
        content="Start/Run illuminated solid green; fill food, close lid, press Start/Run.",
        chunk_type=ChunkType.OPERATION_INSTRUCTION,
        score=0.70,
        section_path=["6 Operation & General Maintenance", "6.3 Operation Macerator"],
        metadata={"sql_keyword_source_score": "8.0"},
    )

    reranked = reranker.rerank(query, [overview_chunk, procedure_chunk])

    assert reranked[0].chunk_id == "chunk_procedure"


def test_deterministic_hybrid_reranker_prefers_overview_answer_over_spare_parts_noise() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_003",
        query_text="What does the FWC system do?",
    )
    spare_parts_chunk = make_chunk(
        chunk_id="chunk_parts",
        content="Spare parts list, installation manuals and materials safety data sheets.",
        chunk_type=ChunkType.SPARE_PARTS_TABLE,
        score=0.94,
        section_path=["Title block"],
        metadata={"sql_keyword_source_score": "11.7"},
    )
    answer_chunk = make_chunk(
        chunk_id="chunk_answer",
        content=(
            "The FWC system is designed to collect food waste from attached macerator "
            "stations using vacuum generated by the integrated pump."
        ),
        chunk_type=ChunkType.GENERAL,
        score=0.68,
        section_path=["3 System Introduction", "3.3 What it Does"],
        metadata={"sql_keyword_source_score": "12.0"},
    )

    reranked = reranker.rerank(query, [spare_parts_chunk, answer_chunk])

    assert reranked[0].chunk_id == "chunk_answer"


def test_deterministic_hybrid_reranker_prefers_installation_like_objective_chunk_for_commissioning_query() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_004",
        query_text="What is the objective of commissioning the FWC12?",
        detected_identifiers=["fwc12"],
        chunk_types=[
            ChunkType.INSTALLATION_INSTRUCTION,
            ChunkType.OPERATION_INSTRUCTION,
            ChunkType.MAINTENANCE_PROCEDURE,
            ChunkType.TECHNICAL_SPECIFICATION,
        ],
    )
    noisy_parts_chunk = make_chunk(
        chunk_id="chunk_parts",
        content="Spare parts list and plant drawings for the FWC12 system.",
        chunk_type=ChunkType.SPARE_PARTS_TABLE,
        score=0.96,
        section_path=["Title block"],
        metadata={"sql_keyword_source_score": "19.35"},
    )
    objective_chunk = make_chunk(
        chunk_id="chunk_objective",
        content=(
            "The overall objective of commissioning is to ensure that the components "
            "of the system are complete, fit for purpose and ready to be set to work."
        ),
        chunk_type=ChunkType.INSTALLATION_INSTRUCTION,
        score=0.73,
        section_path=["5 Commissioning", "5.2 Objective"],
        metadata={"sql_keyword_source_score": "18.9"},
    )

    reranked = reranker.rerank(query, [noisy_parts_chunk, objective_chunk])

    assert reranked[0].chunk_id == "chunk_objective"


def test_deterministic_hybrid_reranker_weighs_structured_match_count() -> None:
    """A chunk carrying structured_match_count metadata (set by
    StructuredEvidenceResolver -- an identifier/entity/related-entity hit)
    should meaningfully outrank an otherwise-identical chunk with no
    structured signal at all, not just get lost in best_source_score's raw
    scale (which is tuned around sql_keyword's much larger magnitude)."""
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_005",
        query_text="Who is the manufacturer of the spare part?",
    )
    plain_chunk = make_chunk(
        chunk_id="chunk_plain",
        content="General notes about spare parts and manufacturers.",
        chunk_type=ChunkType.GENERAL,
        score=0.80,
        section_path=["General Notes"],
    )
    structured_chunk = make_chunk(
        chunk_id="chunk_structured",
        content="Manufacturer: Acme Valves Ltd. Country: Germany.",
        chunk_type=ChunkType.GENERAL,
        score=0.80,
        section_path=["General Notes"],
        metadata={"structured_match_count": "2"},
    )

    reranked = reranker.rerank(query, [plain_chunk, structured_chunk])

    assert reranked[0].chunk_id == "chunk_structured"


def test_deterministic_hybrid_reranker_prefers_direct_schedule_table_over_overview_for_table_like_maintenance_query() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_006",
        query_text="What are the maintenance intervals schedule table?",
    )
    overview_chunk = make_chunk(
        chunk_id="chunk_overview",
        content="Section overview: the maintenance schedule table is shown below.",
        chunk_type=ChunkType.OVERVIEW,
        score=0.95,
        section_path=["Maintenance", "Schedule"],
        metadata={"sql_keyword_source_score": "10.0"},
    )
    schedule_chunk = make_chunk(
        chunk_id="chunk_schedule",
        content="Task | Daily | Weekly\nInspect basket | x |",
        chunk_type=ChunkType.MAINTENANCE_INTERVAL,
        score=0.71,
        section_path=["Maintenance", "Schedule"],
        metadata={
            "sql_keyword_source_score": "8.0",
            "logical_table_family_id": "table_family_001",
            "table_category": "maintenance_interval_table",
            "table_category_confidence": "0.96",
            "table_ids": "[\"table_001\"]",
        },
    )

    reranked = reranker.rerank(query, [overview_chunk, schedule_chunk])

    assert reranked[0].chunk_id == "chunk_schedule"


def test_deterministic_hybrid_reranker_prefers_direct_specification_table_for_technical_data_query() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_007",
        query_text="Show the technical data table.",
    )
    reference_chunk = make_chunk(
        chunk_id="chunk_reference",
        content="See technical data table below for the operating values.",
        chunk_type=ChunkType.GENERAL,
        score=0.93,
        section_path=["Technical Data"],
        metadata={"sql_keyword_source_score": "11.0"},
    )
    spec_chunk = make_chunk(
        chunk_id="chunk_spec",
        content="Parameter | Value\nPressure range | 0...10 bar",
        chunk_type=ChunkType.TECHNICAL_SPECIFICATION,
        score=0.72,
        section_path=["Technical Data"],
        metadata={
            "sql_keyword_source_score": "9.0",
            "logical_table_family_id": "table_family_002",
            "table_category": "technical_data_table",
            "table_category_confidence": "0.90",
            "table_ids": "[\"table_002\"]",
        },
    )

    reranked = reranker.rerank(query, [reference_chunk, spec_chunk])

    assert reranked[0].chunk_id == "chunk_spec"


def test_deterministic_hybrid_reranker_prefers_direct_identifier_table_for_listing_query() -> None:
    reranker = DeterministicHybridReranker()
    query = RetrievalQuery(
        query_id="query_008",
        query_text="List all serial and part numbers.",
    )
    generic_chunk = make_chunk(
        chunk_id="chunk_generic",
        content="Serial and part numbers are listed in the table below.",
        chunk_type=ChunkType.GENERAL,
        score=0.94,
        section_path=["Spare Parts"],
        metadata={"sql_keyword_source_score": "12.0"},
    )
    table_chunk = make_chunk(
        chunk_id="chunk_table",
        content="Part No. | Serial Number\nA00103 | D4093386",
        chunk_type=ChunkType.SPARE_PARTS_TABLE,
        score=0.70,
        section_path=["Spare Parts"],
        metadata={
            "sql_keyword_source_score": "8.0",
            "logical_table_family_id": "table_family_003",
            "table_category": "spare_parts_table",
            "table_category_confidence": "0.91",
        },
    )

    reranked = reranker.rerank(query, [generic_chunk, table_chunk])

    assert reranked[0].chunk_id == "chunk_table"
