"""create initial schema

Revision ID: 4b296c6c1d6a
Revises: 
Create Date: 2026-06-18 00:22:40.168435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b296c6c1d6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('classification_model', sa.String(), nullable=True),
    sa.Column('question_generation_model', sa.String(), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_content_hash'), 'ingestion_runs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_document_id'), 'ingestion_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_file_hash'), 'ingestion_runs', ['file_hash'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_source_id'), 'memory_entries', ['source_id'], unique=False)
    op.create_table('semantic_memory_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_memory_references_source_id'), 'semantic_memory_references', ['source_id'], unique=False)
    op.create_index(op.f('ix_semantic_memory_references_vector_id'), 'semantic_memory_references', ['vector_id'], unique=False)
    op.create_table('document_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('predicted_label', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_classifications_document_id'), 'document_classifications', ['document_id'], unique=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_results_document_id'), 'extraction_results', ['document_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_section_id', sa.String(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('reading_order_start', sa.Integer(), nullable=True),
    sa.Column('reading_order_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_document_id'), 'sections', ['document_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_total', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('token_count_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_section_id'), 'chunks', ['section_id'], unique=False)
    op.create_table('elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('parent_section_id', sa.String(), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('table_id', sa.String(), nullable=True),
    sa.Column('picture_id', sa.String(), nullable=True),
    sa.Column('raw_source_type', sa.String(), nullable=True),
    sa.Column('raw_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_document_id'), 'elements', ['document_id'], unique=False)
    op.create_index(op.f('ix_elements_parent_section_id'), 'elements', ['parent_section_id'], unique=False)
    op.create_table('chunk_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_type', sa.String(), nullable=False),
    sa.Column('predicted_label', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_classifications_chunk_id'), 'chunk_classifications', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_classifications_document_id'), 'chunk_classifications', ['document_id'], unique=False)
    op.create_table('chunk_vectors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('qdrant_collection', sa.String(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_text_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_point_id')
    )
    op.create_index(op.f('ix_chunk_vectors_chunk_id'), 'chunk_vectors', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_vectors_document_id'), 'chunk_vectors', ['document_id'], unique=False)
    op.create_table('equipment_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('manufacturer_name', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_info_document_id'), 'equipment_info', ['document_id'], unique=False)
    op.create_index(op.f('ix_equipment_info_extraction_id'), 'equipment_info', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_equipment_info_model_number'), 'equipment_info', ['model_number'], unique=False)
    op.create_index(op.f('ix_equipment_info_serial_number'), 'equipment_info', ['serial_number'], unique=False)
    op.create_index(op.f('ix_equipment_info_source_chunk_id'), 'equipment_info', ['source_chunk_id'], unique=False)
    op.create_table('generated_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_questions_chunk_id'), 'generated_questions', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_document_id'), 'generated_questions', ['document_id'], unique=False)
    op.create_table('identifiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('element_id', sa.String(), nullable=True),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identifiers_chunk_id'), 'identifiers', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_identifiers_document_id'), 'identifiers', ['document_id'], unique=False)
    op.create_index(op.f('ix_identifiers_element_id'), 'identifiers', ['element_id'], unique=False)
    op.create_index(op.f('ix_identifiers_normalized_value'), 'identifiers', ['normalized_value'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_document_id'), 'maintenance_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_extraction_id'), 'maintenance_tasks', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_source_chunk_id'), 'maintenance_tasks', ['source_chunk_id'], unique=False)
    op.create_table('manufacturers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_document_id'), 'manufacturers', ['document_id'], unique=False)
    op.create_index(op.f('ix_manufacturers_extraction_id'), 'manufacturers', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=False)
    op.create_index(op.f('ix_manufacturers_source_chunk_id'), 'manufacturers', ['source_chunk_id'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('manufacturer_name', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_document_id'), 'spare_parts', ['document_id'], unique=False)
    op.create_index(op.f('ix_spare_parts_extraction_id'), 'spare_parts', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_spare_parts_source_chunk_id'), 'spare_parts', ['source_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_parts_source_chunk_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_extraction_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_document_id'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_manufacturers_source_chunk_id'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_extraction_id'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_document_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_maintenance_tasks_source_chunk_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_extraction_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_document_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_identifiers_normalized_value'), table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_element_id'), table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_document_id'), table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_chunk_id'), table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index(op.f('ix_generated_questions_document_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_chunk_id'), table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_index(op.f('ix_equipment_info_source_chunk_id'), table_name='equipment_info')
    op.drop_index(op.f('ix_equipment_info_serial_number'), table_name='equipment_info')
    op.drop_index(op.f('ix_equipment_info_model_number'), table_name='equipment_info')
    op.drop_index(op.f('ix_equipment_info_extraction_id'), table_name='equipment_info')
    op.drop_index(op.f('ix_equipment_info_document_id'), table_name='equipment_info')
    op.drop_table('equipment_info')
    op.drop_index(op.f('ix_chunk_vectors_document_id'), table_name='chunk_vectors')
    op.drop_index(op.f('ix_chunk_vectors_chunk_id'), table_name='chunk_vectors')
    op.drop_table('chunk_vectors')
    op.drop_index(op.f('ix_chunk_classifications_document_id'), table_name='chunk_classifications')
    op.drop_index(op.f('ix_chunk_classifications_chunk_id'), table_name='chunk_classifications')
    op.drop_table('chunk_classifications')
    op.drop_index(op.f('ix_elements_parent_section_id'), table_name='elements')
    op.drop_index(op.f('ix_elements_document_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_chunks_section_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_sections_document_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_extraction_results_document_id'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_document_classifications_document_id'), table_name='document_classifications')
    op.drop_table('document_classifications')
    op.drop_index(op.f('ix_semantic_memory_references_vector_id'), table_name='semantic_memory_references')
    op.drop_index(op.f('ix_semantic_memory_references_source_id'), table_name='semantic_memory_references')
    op.drop_table('semantic_memory_references')
    op.drop_index(op.f('ix_memory_entries_source_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_ingestion_runs_file_hash'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_document_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_content_hash'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_table('conversation_memories')
    # ### end Alembic commands ###
