"""add audit records

Revision ID: 4dd4a5547716
Revises: d6aa2b014259
Create Date: 2026-06-18 20:09:42.212501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd4a5547716'
down_revision: Union[str, Sequence[str], None] = 'd6aa2b014259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('before_state_json', sa.Text(), nullable=True),
    sa.Column('after_state_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_action'), 'audit_records', ['action'], unique=False)
    op.create_index(op.f('ix_audit_records_actor_id'), 'audit_records', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_records_correlation_id'), 'audit_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_records_created_at'), 'audit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_records_entity_id'), 'audit_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_records_entity_type'), 'audit_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_records_outcome'), 'audit_records', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_records_request_id'), 'audit_records', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_records_severity'), 'audit_records', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_severity'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_request_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_outcome'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_entity_type'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_entity_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_created_at'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_correlation_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_actor_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_action'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
