"""add activity records

Revision ID: d6aa2b014259
Revises: 4b296c6c1d6a
Create Date: 2026-06-18 10:01:58.365289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6aa2b014259'
down_revision: Union[str, Sequence[str], None] = '4b296c6c1d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_records_action'), 'activity_records', ['action'], unique=False)
    op.create_index(op.f('ix_activity_records_actor_id'), 'activity_records', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_records_correlation_id'), 'activity_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_activity_records_created_at'), 'activity_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_records_entity_id'), 'activity_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_records_entity_type'), 'activity_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_records_request_id'), 'activity_records', ['request_id'], unique=False)
    op.create_index(op.f('ix_activity_records_severity'), 'activity_records', ['severity'], unique=False)
    op.create_index(op.f('ix_activity_records_status'), 'activity_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_records_status'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_severity'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_request_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_entity_type'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_entity_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_created_at'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_correlation_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_actor_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_action'), table_name='activity_records')
    op.drop_table('activity_records')
    # ### end Alembic commands ###
