"""add event envelopes

Revision ID: f3c55ae893eb
Revises: 4dd4a5547716
Create Date: 2026-06-18 20:50:30.409357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c55ae893eb'
down_revision: Union[str, Sequence[str], None] = '4dd4a5547716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_envelopes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=True),
    sa.Column('aggregate_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_envelopes_actor_id'), 'event_envelopes', ['actor_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_aggregate_id'), 'event_envelopes', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_aggregate_type'), 'event_envelopes', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_event_envelopes_correlation_id'), 'event_envelopes', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_event_type'), 'event_envelopes', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_envelopes_occurred_at'), 'event_envelopes', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_event_envelopes_request_id'), 'event_envelopes', ['request_id'], unique=False)
    op.create_index(op.f('ix_event_envelopes_severity'), 'event_envelopes', ['severity'], unique=False)
    op.create_index(op.f('ix_event_envelopes_status'), 'event_envelopes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_envelopes_status'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_severity'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_request_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_occurred_at'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_event_type'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_correlation_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_aggregate_type'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_aggregate_id'), table_name='event_envelopes')
    op.drop_index(op.f('ix_event_envelopes_actor_id'), table_name='event_envelopes')
    op.drop_table('event_envelopes')
    # ### end Alembic commands ###
