from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part1 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part2 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part3 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part4 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part5 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part6 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part7 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part8 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part9 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part10 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part11 import *  # noqa: F401,F403
from tests.unit.application.workflows.parsing.builders._test_document_graph_builder_part12 import *  # noqa: F401,F403
