from enum import StrEnum


class StructuredEvidenceFamily(StrEnum):
    DRAWING_TITLE_BLOCK = "drawing_title_block"
    DRAWING_VESSEL_PARTICULARS = "drawing_vessel_particulars"
    DRAWING_REVISION_TABLE = "drawing_revision_table"
    DRAWING_COMPLIANCE_TABLE = "drawing_compliance_table"
    DRAWING_LABEL_BLOCK = "drawing_label_block"
    DRAWING_EQUIPMENT_LEGEND = "drawing_equipment_legend"
    CERTIFICATE_GENERAL_INFORMATION = "certificate_general_information"
    CERTIFICATE_PARTICULARS = "certificate_particulars"
    CERTIFICATE_COMPLIANCE_INFORMATION = "certificate_compliance_information"
    CERTIFICATE_APPROVAL_INFORMATION = "certificate_approval_information"
    CERTIFICATE_TEST_DATA = "certificate_test_data"
    DATASHEET_TECHNICAL_DATA = "datasheet_technical_data"
    DATASHEET_SPECIFICATION_TABLE = "datasheet_specification_table"
    DATASHEET_ORDERING_INFORMATION = "datasheet_ordering_information"
    DATASHEET_ORDERING_EXAMPLE = "datasheet_ordering_example"
    DATASHEET_CONNECTION_INFORMATION = "datasheet_connection_information"
    DATASHEET_OPERATING_LIMITS = "datasheet_operating_limits"
    DATASHEET_PRESSURE_TEMPERATURE_DATA = "datasheet_pressure_temperature_data"
    DATASHEET_MATERIAL_INFORMATION = "datasheet_material_information"
    REPORT_DEVICE_INFORMATION = "report_device_information"
    REPORT_ADDITIONAL_INFORMATION = "report_additional_information"
    REPORT_INSPECTION_RESULTS = "report_inspection_results"
    REPORT_CALIBRATION_RESULTS = "report_calibration_results"
    REPORT_ELECTRICAL_CONNECTION = "report_electrical_connection"
    REPORT_OPERATING_INSTRUCTIONS = "report_operating_instructions"
    REPORT_CERTIFICATION_SECTION = "report_certification_section"
    MANUAL_OPERATION_PROCEDURE = "manual_operation_procedure"
    MANUAL_MAINTENANCE_PROCEDURE = "manual_maintenance_procedure"
    MANUAL_MAINTENANCE_INTERVAL = "manual_maintenance_interval"
    MANUAL_TROUBLESHOOTING = "manual_troubleshooting"
    MANUAL_SPARE_PARTS = "manual_spare_parts"
    MANUAL_COMMISSIONING = "manual_commissioning"
    MANUAL_SHUTDOWN = "manual_shutdown"
    MANUAL_SAFETY_INSTRUCTIONS = "manual_safety_instructions"
    MANUAL_LUBRICATION = "manual_lubrication"
    MANUAL_INSTALLATION = "manual_installation"
    SENSOR_LIST = "sensor_list"
    INSTRUMENT_LIST = "instrument_list"
    TAG_LIST = "tag_list"
    PID_LIST = "pid_list"
    IO_LIST = "io_list"
    APPROVAL_INFORMATION = "approval_information"
