from enum import StrEnum


class RetrievalStrategy(StrEnum):
    GENERAL_HYBRID = "GENERAL_HYBRID"
    IDENTIFIER_LOOKUP = "IDENTIFIER_LOOKUP"
    TECHNICAL_SPECIFICATION = "TECHNICAL_SPECIFICATION"
    TABLE_LOOKUP = "TABLE_LOOKUP"
    SECTION_LOOKUP = "SECTION_LOOKUP"
    MAINTENANCE_LOOKUP = "MAINTENANCE_LOOKUP"
    PROCEDURE_LOOKUP = "PROCEDURE_LOOKUP"
    TROUBLESHOOTING_LOOKUP = "TROUBLESHOOTING_LOOKUP"
    CERTIFICATION_LOOKUP = "CERTIFICATION_LOOKUP"
    DRAWING_LOOKUP = "DRAWING_LOOKUP"
    FIGURE_LOOKUP = "FIGURE_LOOKUP"
    DOCUMENT_EXPLORATION = "DOCUMENT_EXPLORATION"
    MULTI_STRATEGY = "MULTI_STRATEGY"
